---
title: "Suicidal Data Analysis with Visualization"
author: "Dedy Gusnadi Sianipar"
date: "3/30/2021"
output:
  rmdformats::downcute:
    self_contained: yes
    thumbnails: no
    lightbox: yes
    gallery: yes
    highlight: kate
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Pendahuluan
##        {.tabset .tabset-fade .tabset-pills}

### 1.1 Latar Belakang
  Berikut ini merupakan data dari daftar kasus bunuh diri dari berbagai negara dengan waktu terntentu

### 1.2 Data's Point of View


# Load Library Package
```{r, message=FALSE,fig.dim=c(10,10)}
library(tidyverse)
library(lubridate)
library(ggplot2)
options(scipen = 9999)
```




```{r}
suicide <- read.csv("data_input/who_suicide_statistics.csv")
glimpse(suicide)
```

```{r}
df <- suicide %>%
  mutate_if(is.character,as.factor) 
df1 <- df %>% 
  select(-population) %>% 
  mutate(suicides_no =ifelse(is.na(suicides_no), yes = 0, no = suicides_no))
df2 <- df1 %>% rename(.data = .,suicides=suicides_no)
str(df1)
```
EDA
```{r}
unique(df2$country)
sum(df2$suicides)
```
suicide per year

```{r}
df2 %>% 
  group_by(year) %>%
  summarise(kasus = sum(suicides)) %>% 
  ggplot(aes(x=year,y=kasus,col="red"))+
  geom_line(size=1.5)+
  labs(title = "Year-Based Suicides",
       subtitle = "from 1985 until 2016",
       y = "Cumulative Death",
       x = "Year")+
  theme(legend.position = "none")

```



suicides per Year across genders
```{r,warning=TRUE}
df2 %>% 
  group_by(sex,year) %>% 
  summarise(kasus = sum(suicides)) %>% 
  ungroup() %>% 
  ggplot(aes(x=year,y=kasus,col=sex))+
  geom_line(size=1.5)+
  labs(title = "Graph Sex-Based Suicide",
       subtitle = "from 1985 until 2016",
       y = "Cumulative Death",
       x = "year")+
  theme(legend.position = "none")
```
total suicides by year acrros age groups
```{r}
df2 %>% 
  group_by(age,sex) %>% 
  summarise(kasus = sum(suicides)) %>% 
  ungroup() %>%
  ggplot(aes(x=sex,y=kasus))+
  geom_col(aes(fill=age),position = "dodge")+
  labs(title = "Graph Sex & Age-Based Suicides",
       subtitle = "from 1985 until 2016",
       x = "sex",
       y = "Cumulative Suicides")
```
```{r}
df2 %>% 
  group_by(age,year) %>% 
  summarise(kasus = sum(suicides)) %>% 
  ungroup() %>%
  ggplot(aes(x=year,y=kasus))+
  geom_line(aes(col=age),size=1.5)+
   labs(title = "Plot age-based suicides",
       subtitle = "from 1985 until 2016",
       x = "Year",
       y = "Suicides")
```
top 10 county total suicides
```{r}
df2 %>% 
  group_by(country) %>% 
  summarise(total = sum(suicides)) %>% 
  top_n(10) %>% 
  ggplot(aes(x=total,y=reorder(country,total)))+
  geom_col(fill="firebrick")+
   labs(title = "Top 10 Country Suicides",
       subtitle = "from 1985 until 2016",
       x = "Cumulative Death",
       y = "Country")+
  theme(legend.position = "none")
```
```{r}
df2 %>%
  filter(sex %in% "female") %>% 
  group_by(country) %>% 
  summarise(total = sum(suicides)) %>% 
  top_n(10) %>% 
  ggplot(aes(x=total, y=reorder(country,total), fill="firebrick"))+
  geom_col()+
  labs(title = "Top 10 Country Woman Suicides",
       subtitle = "from 1985 until 2016",
       x = "Cumulative Death",
       y = "Country")+
  theme(legend.position = "none")
```
```{r}
df2 %>%
  filter(sex %in% "male") %>% 
  group_by(country) %>% 
  summarise(total = sum(suicides)) %>% 
  top_n(10) %>% 
  ggplot(aes(x=total, y=reorder(country,total), fill="firebrick"))+
  geom_col()+
  labs(title = "Top 10 Country Male Suicides",
       subtitle = "from 1985 until 2016",
       x = "Cumulative Death",
       y = "Country")+
  theme(legend.position = "none")
```

